<?php
/**
 * Created by PhpStorm.
 * User: zhy
 * Date: 2019/2/15
 * Time: 16:48
 */

namespace App\HttpController;


use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Http\Message\Status;

class Index extends Controller
{
    protected function onRequest(string $action): ?bool
    {
        var_dump($this->request()->getHeaders());
        $this->response()->withStatus(Status::CODE_FORBIDDEN);
        return false;
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    function index()
    {
        // TODO: Implement index() method.
        $this->response()->write('hello laozaoyin');
    }

    function test()
    {
        $this->response()->write('this is test');
    }

}